#@TYPE: Machine
#@NAME: Raspberry Pi 4 Emulator
#@DESCRIPTION: Machine configuration for Raspberry Pi 4 Emulator
# https://docs.yoctoproject.org/dev-manual/new-machine.html


# Make sure virtio is enabled in the kernel configuration!
# When using a default kernel, check if cfg/virtio.scc from
# the Yocto kernel config cache is included (https://git.yoctoproject.org/yocto-kernel-cache)
# Vendor specific kernels like linux-raspberrypi may not support
# the related KERNEL_FEATURES variable - include a matching configuration manually!
# see meta-training-bsp/recipes-kernel!
require conf/machine/raspberrypi4-64.conf

MACHINEOVERRIDES =. "emu:"
SERIAL_CONSOLES = "115200;ttyAMA0 115200;hvc0"


EXTRA_IMAGEDEPENDS += "qemu-native qemu-helper-native"
IMAGE_CLASSES += "qemuboot"

QB_SYSTEM_NAME = "qemu-system-aarch64"
QB_MACHINE = "-machine virt"
QB_CPU = "-cpu cortex-a72"
QB_SMP = "-smp 4"
QB_MEM = "-m 2048"
QB_DEFAULT_FSTYPE = "ext3"
QB_GRAPHICS = "-device virtio-gpu-pci"
QB_OPT_APPEND = "-device qemu-xhci -device usb-tablet -device usb-kbd"
QB_TAP_OPT = "-netdev tap,id=net0,ifname=@TAP@,script=no,downscript=no"
QB_NETWORK_DEVICE = "-device virtio-net-pci,netdev=net0,mac=@MAC@"
QB_ROOTFS_OPT = "-drive id=disk0,file=@ROOTFS@,if=none,format=raw -device virtio-blk-pci,drive=disk0"
QB_SERIAL_OPT = "-device virtio-serial-pci -chardev null,id=virtcon -device virtconsole,chardev=virtcon"
QB_TCPSERIAL_OPT = "-device virtio-serial-pci -chardev socket,id=virtcon,port=@PORT@,host=127.0.0.1,nodelay=on -device virtconsole,chardev=virtcon"

