# https://docs.yoctoproject.org/dev-manual/custom-distribution.html

#### General distro metadata ####
DISTRO = "training-distro"
DISTRO_NAME = "inovex Training Distro"
DISTRO_VERSION = "1.0.0"
DISTRO_CODENAME = "Squirrel"

TARGET_VENDOR = "-inovex"

SDK_VENDOR = "-trainingdistrosdk"
SDK_VERSION = "${DISTRO_VERSION}"

MAINTAINER = "Anna-Lena Marx <anna-lena.marx@inovex.de>"


#### Configure package class and init manager ####
PACKAGE_CLASSES = "package_deb"
INIT_MANAGER = "systemd"

#### Configure the ToolChain LibC ####
# TCLIBC = "musl"
TCLIBC = "glibc"


#### Distro features ####
DISTRO_FEATURES:append = " \
    \
"

DISTRO_FEATURES:remove = "opengl"
DISTRO_FEATURES:remove = "wayland"
# DISTRO_FEATURES:remove = "x11"


#### Standard include files, mostly security related ####
require conf/distro/include/no-static-libs.inc
require conf/distro/include/yocto-uninative.inc
require conf/distro/include/security_flags.inc
require conf/distro/include/rust_security_flags.inc

INHERIT += "uninative"

#### Hash server configuration ####
BB_SIGNATURE_HANDLER = "OEEquivHash"
BB_HASHSERVE = "auto"
BB_HASHSERVE_UPSTREAM = 'wss://hashserv.yoctoproject.org/ws'
SSTATE_MIRRORS = "file://.* http://sstate.yoctoproject.org/all/PATH;downloadfilename=PATH"


#### License configuration ####
COPY_LIC_MANIFEST = "1"
COPY_LIC_DIRS = "1"
LICENSE_CREATE_PACKAGE = "1"

#### Generate a SPDX SBoM ####
INHERIT += "create-spdx"

SPDX_PRETTY = "1"
SPDX_INCLUDE_SOURCES = "1"
SPDX_ARCHIVE_SOURCES = "1"

SPDX_SUPPLIED = "Organization: inovex GmbH"
SPDX_NAMESPACE_PREFIX = "http://inovex.de/spdx"
SPDX_UUID_NAMESPACE = "inovex.de"

#### Source archiver ####
# Utilize the archiver to generate a source archive for a release
INHERIT += "archiver"
ARCHIVER_MODE[src] = "original"

#### Utilize the Yocto CVE checker ####
include conf/distro/include/cve-extra-exclusions.inc
INHERIT += "cve-check"

#### Enable build history ####
INHERIT += "buildhistory"
BUILDHISTORY_COMMIT = "1"
