# https://docs.yoctoproject.org/dev-manual/custom-distribution.html

#### General distro metadata ####
DISTRO = "training-distro"
DISTRO_NAME = "inovex Training Distro"
DISTRO_VERSION = "1.0.0"
DISTRO_CODENAME = "Squirrel"

TARGET_VENDOR = "-inovex"

SDK_VENDOR = "-trainingdistrosdk"
SDK_VERSION = "${DISTRO_VERSION}"

MAINTAINER = "Anna-Lena Marx <anna-lena.marx@inovex.de>"


#### Configure package class and init manager ####
PACKAGE_CLASSES = "package_deb"
INIT_MANAGER = "systemd"

#### Configure the ToolChain LibC ####
# TCLIBC = "musl"
TCLIBC = "glibc"


#### Distro features ####
DISTRO_FEATURES:append = " \
    \
"

# Both are in DISTRO_FEATURES_DEFAULTS by now and not needed for the training distro
DISTRO_FEATURES_OPTED_OUT:append = " opengl  wayland"
# Opt out to all defaults
# DISTRO_FEATURES_OPTED_OUT = "*"


#### Standard include files, rust security example ####
require conf/distro/include/rust_security_flags.inc

INHERIT += "uninative"

#### Use prebuilt sstate artifacts for standard Yocto build configurations ####
# OE_FRAGMENTS += "core/yocto/sstate-mirror-cdn"

#### License configuration ####
COPY_LIC_MANIFEST = "1"
COPY_LIC_DIRS = "1"
LICENSE_CREATE_PACKAGE = "1"

#### SPDX SBoM options ####
SPDX_PRETTY = "1"
SPDX_INCLUDE_SOURCES = "1"
SPDX_ARCHIVE_SOURCES = "1"
SPDX_INCLUDE_KERNEL_CONFIG = "1"
SPDX_INCLUDE_PACKAGECONFIG = "1"

SPDX_INCLUDE_VEX = "all"

SPDX_SUPPLIED = "Organization: inovex GmbH"
SPDX_NAMESPACE_PREFIX = "http://inovex.de/spdx"
SPDX_UUID_NAMESPACE = "inovex.de"

#### Source archiver ####
# Utilize the archiver to generate a source archive for a release
INHERIT += "archiver"
ARCHIVER_MODE[src] = "original"

#### Utilize the Yocto CVE checker ####
OE_FRAGMENTS += "core/yocto/sbom-cve-check"
require conf/distro/include/cve-extra-exclusions.inc

#### Enable build history ####
INHERIT += "buildhistory"
BUILDHISTORY_COMMIT = "1"
