#@TYPE: Machine
#@NAME: EDA Tec CM4 Sensing
#@DESCRIPTION: Machine configuration for EDA Technology CM4 Sensing

# https://docs.yoctoproject.org/dev-manual/new-machine.html

MACHINEOVERRIDES =. "cm4-sensing"

require conf/machine/raspberrypi4-64.conf

PREFERRED_PROVIDER_virtual/kernel:cm4-sensing ?= "linux-raspberrypi"

MACHINE_FEATURES:append = " \
    \
"

RPI_KERNEL_DEVICETREE:append = " \
    \
"

IMAGE_FSTYPES:append = ""
