header:
  version: 18
  includes:
    - config/base.yml

repos:
  meta-arm:
    url: https://git.yoctoproject.org/meta-arm
    path: "layers/meta-arm"
    layers:
      meta-arm:
      meta-arm-toolchain:

  meta-imx:
    url: https://github.com/nxp-imx/meta-imx.git
    branch: ""
    tag: rel_imx_6.6.23_2.0.0
    # branch: scarthgap-6.6.52-2.2.0
    path: "layers/meta-imx"
    layers:
      meta-imx-bsp:

  meta-freescale:
    url: https://github.com/Freescale/meta-freescale.git
    path: "layers/meta-freescale"

  meta-compulab-bsp:
    url: https://github.com/compulab-yokneam/meta-compulab-bsp.git
    branch: honister
    path: "layers/meta-compulab-bsp"
    layers:
      meta-bsp:

  meta-bsp-imx8mm:
    url: https://github.com/compulab-yokneam/meta-bsp-imx8mm
    branch: ""
    tag: iot-gate-imx8-r4.1
    path: "layers/meta-bsp-imx8mm"


machine: iot-gate-imx8

local_conf_header:
  imx8mm: |
    ACCEPT_FSL_EULA = "1"

    HOSTTOOLS:remove = "bison git-lfs"

    BBMASK += "nxp-demo-experience_%.bbappend"
    BBMASK += "cryptodev-linux_1.13.bbappend"
    BBMASK += "xwayland_23.1.1.imx.bbappend"
    BBMASK += "wireplumber_%.bbappend"
    BBMASK += "pipewire_%.bbappend"
    BBMASK += "qemu_8.2.2.imx.bb"
    BBMASK += "firmware-nxp-wifi_1.1.bb"
    BBMASK += "firmware-nxp-wifi_%.bbappend"

    IMAGE_INSTALL:remove = "imx-m4-demos"
    IMAGE_INSTALL:remove = "imx-sw-pdm"
    IMAGE_INSTALL:remove = "imx-gpu-viv-demos"

