header:
  version: 19

repos:
  meta-training-rpi-bsp:
    path: layers/meta-training/meta-training-rpi-bsp

  meta-raspberrypi:
    url: https://github.com/agherzan/meta-raspberrypi.git
    path: "layers/meta-raspberrypi"
    branch: master

  meta-mender-community:
    url: https://github.com/mendersoftware/meta-mender-community.git
    path: "layers/meta-mender-community"
    branch: wrynose
    layers:
      meta-mender-raspberrypi:

local_conf_header:
  raspberrypi: |
    RPI_USE_U_BOOT = "1"
    ENABLE_UART = "1"
    IMAGE_FSTYPES:remove = " rpi-sdimg"
    SDIMG_ROOTFS_TYPE = "ext4"
    LICENSE_FLAGS_ACCEPTED = "synaptics-killswitch"

