header:
  version: 18
  includes:
    - config/base.yml
    - config/raspberrypi.yml


local_conf_header:
  raspberrypi3: |
    MACHINE_FEATURES:append = " vc4graphics"
    VC4DTBO := "vc4-kms-v3d"

    # Set kernel device tree for Raspberry Pi 3
    KERNEL_DEVICETREE = "broadcom/bcm2710-rpi-3-b-plus.dtb"

    # Select device tree overlays for DRM Display devices needed by flutter-pi
    KERNEL_DEVICETREE:append = " overlays/vc4-kms-v3d.dtbo"
    KERNEL_DEVICETREE:append = " overlays/vc4-kms-dsi-7inch.dtbo"

    # Add the 7inch display overlay to config.txt to enable touch
    RPI_EXTRA_CONFIG += '\ndtoverlay=vc4-kms-dsi-7inch,invx,invy'

    # Rotate display
    RPI_EXTRA_CONFIG += '\nlcd_rotate=2'

    # Install both overlays to boot partition
    IMAGE_BOOT_FILES:append = " vc4-kms-v3d.dtbo"
    IMAGE_BOOT_FILES:append = " vc4-kms-dsi-7inch.dtbo"

    CMDLINE:prepend = " video=DSI-1:800x480@30,rotate=180"


machine: raspberrypi3-64

